# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Install dependencies and build
WORKDIR /app
# Install bash and shx for setup script
RUN apk add --no-cache bash

# Copy project files
COPY package.json pnpm-lock.yaml tsconfig.json setup.sh ./
COPY src/ ./src/

# Install dependencies and build TypeScript
RUN npm install && npm run build

# Default command
CMD ["node", "dist/index.js"]
